language: R
cache: packages
sudo: required
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then tlmgr install boxedminipage; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr install a4wide boxedminipage framed; fi
deploy:
  provider: releases
  api_key:
    secure: uG9LvBfM0tg4KzUHTzwg8hWAsTtxIx7huKXL6QNuUqSqWp64AyxcY9vo4wvs0KrfFPNdSBpovCyxJCZO4yFmkB+rxrgPPwGv7AhXNEEnRzi54PkXYQIpOyRjJ9KPY66fGj+stPL7RxIOTRxuLPnnUL5VSvXF99ka5AHLNnYlgnf2XZdQIcgd7MrEB/T+2/1rwOiGTNjTnzcobDGU5piP44Mitm4sxkYkr0WeIxVw53jIpXG4zjEJrmlEMiNxu15yS+K6B91Lpp9C+qY4Z7+W+0EtQzgo1tWUW8VSodWykNItJ/HZz9KxQFg7360cjbfKGfiP8AkvywyZw4xKsQLaDzjSMypqwXhjqV/Yf3v30AFOjupOMVCWoRbE6PvZv1TcnHf9T1UgnqK2Ng4Oucm0KeLvKBrxtC56eDA9hiGfoTS4RS6vD4AnvqQ5IntwS3HCrgmgbAQjS/SkIOFtEx5zqDOUnarrejzDcpfJKeXYgl2xVJEqA38bn2KYCnFoCDYW0sOYyxdV3zIbcBL4Fgr+CqW/b66Jql8lgRuI+1hCngLlvB+5Kqs0zy6UA/XHb2S2nOrY9WUVFnwlR5pmBk4DpTL4tc6min+H/fvV4xW4GuFqBQ2LB4mvPrziGt4Hc9L1iWM5mj9ZeSTMzSzBgobnX+BZATQ/sNASx6wo0tsOpgI=
  skip_cleanup: true
  file_glob: true
  file: doBy_*.t*gz
  on:
    repo: hojsgaard/doBy
    tags: true
    condition: "$TRAVIS_OS_NAME == osx"
